apiVersion: v1
kind: ConfigMap
metadata:
  name: restaurantproducer-configmap
  namespace: restaurant-dev
data:
  application.yaml: |+
    spring:
      application:
        name: restaurantproducer
      datasource:
        username: user 
        password: password
        url: jdbc:mysql://host.minikube.internal:3306/restaurant
        driver-class-name: com.mysql.cj.jdbc.Driver
    kafka:
      server: host.minikube.internal:29092
      topics:
        restaurant: 
          name: restaurant.topic
          partitions: 2
        served: 
          name: restaurantServed.topic
          partitions: 2
         
    server:
      servlet:
        context-path: /restaurantproducer
