apiVersion: v1
kind: Service
metadata:
  name: restaurantproducer-service
  namespace: restaurant-dev
  labels:
    app: restaurantproducer-label
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007
  selector:
    app: restaurantproducer-deployment
